version: '3.5'
services:
  nginx:
    image: ${GITLAB_PROJECT_URL}/master/nginx:latest
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    environment:
      VIRTUAL_HOST: ${COMPOSE_PROJECT_NAME}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${COMPOSE_PROJECT_NAME}
      LETSENCRYPT_EMAIL: ${CERT_EMAIL}
    expose:
      - 80
    networks:
      - proxy-nginx
      - app

  php:
    image: ${GITLAB_PROJECT_URL}/master/php:latest
    container_name: ${COMPOSE_PROJECT_NAME}_php
    environment:
      - APP_ENV=prod
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASS}@mysql:3306/${COMPOSE_PROJECT_NAME}
    networks:
      sql:
      app:
        aliases:
          - fpm

networks:
  proxy-nginx:
    external:
      name: nginx-proxy
  sql:
    external:
      name: mysql-general
  app:
    name: ${COMPOSE_PROJECT_NAME}
